export const ErrorCodes = {
  AUTH: {
    UNAUTHORIZED: 'AUTH.UNAUTHORIZED',
    FORBIDDEN: 'AUTH.FORBIDDEN',
    TOKEN_INVALID: 'AUTH.TOKEN_INVALID',
    TOKEN_EXPIRED: 'AUTH.TOKEN_EXPIRED',
  },

  REQUEST: {
    VALIDATION_FAILED: 'REQUEST.VALIDATION_FAILED',
    BAD_PARAMS: 'REQUEST.BAD_PARAMS',
    PARSE_ERROR: 'REQUEST.PARSE_ERROR',
  },

  IDENTITY: {
    FORBIDDEN: 'IDENTITY.FORBIDDEN',
    USER_NOT_FOUND: 'IDENTITY.USER_NOT_FOUND',
    EMAIL_EXISTS: 'IDENTITY.EMAIL_EXISTS',
    INVALID_CREDENTIALS: 'IDENTITY.INVALID_CREDENTIALS',
    ROLE_NOT_FOUND: 'IDENTITY.ROLE_NOT_FOUND',
  },

  ROOM: {
    NOT_FOUND: 'ROOM.NOT_FOUND',
    INVALID_SLOT: 'ROOM.INVALID_SLOT_CONFIG',
    FORBIDDEN: 'ROOM.FORBIDDEN',
  },

  BOOKING: {
    NOT_FOUND: 'BOOKING.NOT_FOUND',
    SLOT_TAKEN: 'BOOKING.SLOT_TAKEN',
    BAD_START: 'BOOKING.BAD_START',
    PAST_SLOT: 'BOOKING.PAST_SLOT',
    MISALIGNED_SLOT: 'BOOKING.MISALIGNED_SLOT',
    INVALID_STATE: 'BOOKING.INVALID_STATE',
    EXPIRED: 'BOOKING.EXPIRED',
  },

  AVAILABILITY: {
    INVALID_RANGE: 'AVAILABILITY.INVALID_RANGE',
  },

  NOTIFICATION: {
    SEND_FAILED: 'NOTIFICATION.SEND_FAILED',
  },

  EVENTBUS: {
    PUBLISH_FAILED: 'EVENTBUS.PUBLISH_FAILED',
  },

  SYSTEM: {
    REDIS_UNAVAILABLE: 'SYSTEM.REDIS_UNAVAILABLE',
    DB_ERROR: 'SYSTEM.DB_ERROR',
    UNKNOWN: 'SYSTEM.UNKNOWN',
  },
} as const;
