export const ErrorCodes = {
  // Identity
  IDENTITY: {
    EMAIL_EXISTS: 'IDENTITY.EMAIL_EXISTS',
    USER_NOT_FOUND: 'IDENTITY.USER_NOT_FOUND',
    INVALID_CREDENTIALS: 'IDENTITY.INVALID_CREDENTIALS',
    FORBIDDEN: 'IDENTITY.FORBIDDEN',
  },
  // Room
  ROOM: {
    NOT_FOUND: 'ROOM.NOT_FOUND',
    FORBIDDEN: 'ROOM.FORBIDDEN',
  },
  // Booking
  BOOKING: {
    SLOT_TAKEN: 'BOOKING.SLOT_TAKEN',
    OVERLAP: 'BOOKING.OVERLAP',
    NOT_FOUND: 'BOOKING.NOT_FOUND',
    INVALID_STATE: 'BOOKING.INVALID_STATE',
  },
} as const;